services:
  wespeak-ai:
    build: .
    container_name: wespeak-ai
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      OLLAMA_BASE_URL: http://host-gateway:11434
    extra_hosts:
      - "host-gateway:host-gateway"
    volumes:
      - whisper-models:/root/.cache/huggingface
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped

volumes:
  whisper-models:
